name: ' anco.md'
favicon: null
layout_spectrum: 0.4351750281639397
typography_spectrum: 0.9268871524836868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9974261152092367
  lightness: 0.13719496643170714
  saturation: 0.18337300000712276
  rhythmicContrast: 0.6645042505115271
purpose: []
